### ISSUE TITLE
Loses parts of the changelog

### ISSUE THREAD

**Issue by nomeata** [ddssff/cabal-debian#40]
Hi,

with a bunch of upgrades pending, I’m looking into `cabal-debian` again.

Running it in a freshly checked out `haskell-zlib` folder, I get this
```
/tmp/haskell-zlib-0.5.4.1 $ /home/jojo/build/haskell/cabal-debian/.cabal-sandbox/bin/cabal-debian --compare
Debianization (dry run):
--- old/debian/changelog
+++ new/debian/changelog
@@
-haskell-zlib (0.5.4.1-2) experimental; urgency=low
-
-  * Adjust watch file to new hackage layout
-  * Depend on haskell-devscripts 0.9, found in experimental
-
- -- Joachim Breitner <nomeata@debian.org>  Sat, 20 Dec 2014 17:12:54 +0100
-
 haskell-zlib (0.5.4.1-1) unstable; urgency=low
```

It shouldn’t lose the last changelog entry, should it?

**Comment by ddssff** [comment]
I know there is some historical code that removes existing changelog entries for versions newer than the cabal version, or something of that nature.  I will take a look.

**Comment by ddssff** [comment]
Ok, here's what's happening.  We set the default debian version to <cabal-version>-1 for all quilt format packages where the revision is not explicitly set.  Then when it finalizes the changelog it runs

    (A.debInfo . D.changelog) %= fmap (dropFutureEntries ver)

so any changelog entries newer than <cabal-version>-1 are dropped.  Why, you might ask?  I think its because we were striving to avoid uploading packages that would look newer than forthcoming upstream versions, and debian was upstream for us.

One way to proceed is instead of setting revision to 1, we could get the most recent revision from the changelog if it exists, and set it to 1 if it doesn't, or it is < 1.  That would make the dropFutureEntries call a no-op, so it could be removed.

**Comment by nomeata** [comment]
> One way to proceed is instead of setting revision to 1, we could get the most recent revision from the changelog if it exists, and set it to 1 if it doesn't, or it is < 1. That would make the dropFutureEntries call a no-op, so it could be removed.

Sounds good.

**Comment by ddssff** [comment]
Try version 4.26.

**Comment by ddssff** [comment]
I believe this is fixed.
